### ISSUE TITLE
install.py无法运行

### ISSUE THREAD

**Issue by lnbmo** [cmluZw/Situational-Awareness#4]
本人python3.5
使用python3 install.py时报错
报错如下：
Traceback (most recent call last):
  File "Install.py", line 2, in <module>
    import pymysql
  File "/usr/local/lib/python3.5/dist-packages/pymysql/__init__.py", line 59, in <module>
    from . import connections  # noqa: E402
  File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 206
    ):
    ^
SyntaxError: invalid syntax

**Comment by cmluZw** [comment]
请检测数据库是否正常运行，账号密码，权限等是否正常



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月12日(周一) 晚上10:43
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cmluZw/Situational-Awareness] install.py无法运行 (Issue #4)




 
本人python3.5
 使用python3 install.py时报错
 报错如下：
 Traceback (most recent call last):
 File "Install.py", line 2, in 
 import pymysql
 File "/usr/local/lib/python3.5/dist-packages/pymysql/init.py", line 59, in 
 from . import connections  # noqa: E402
 File "/usr/local/lib/python3.5/dist-packages/pymysql/connections.py", line 206
 ):
 ^
 SyntaxError: invalid syntax

**Comment by cmluZw** [comment]
另请参考：https://blog.csdn.net/hans99812345/article/details/114460783
