### ISSUE TITLE
如遇报错请先看这

### ISSUE THREAD

**Issue by cmluZw** [cmluZw/Situational-Awareness#6]
### 1.[Errno 32]Broken pipe
<br>
一般是在执行install.py时遇到的，解决方法为：<br>
1.控制python版本在3.7-3.9之间<br>
2.不要使用install.py，按照主页说明文档，手动安装<br>
3.百度<br>

### 2.与json相关的错误
<br>
1.安装flask=2.0.2(pip3 install flask==2.0.2)<br>
2.从github替换https://github.com/cmluZw/Situational-Awareness/blob/master/output/analyse/network/flowStatistics.txt这个文件<br>
3.百度<br>

### 3.已经安装过库后依旧报找不到库
<br>
1.查找运行app.py的版本是否是安装库对应的版本<br>
2.百度<br>

### 4.cannot import name ‘Pie’ from ‘Pyecharts’
pyecharts版本安装得太高，只支持0.5.x，重新pip安装requirements.txt<br>

### 5.部署成功后无法显示主页或者主页乱码
1.使用谷歌或者火狐浏览器<br>
2.清空数据库<br>
3.百度<br>

### 在确定版本正确，环境正确，且按照说明文档的安装百度之后依然无法解决，找我

**Comment by work-manong** [comment]
请问一下，各位大佬遇见这种问题吗
with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by work-manong** [comment]
def _is_elf(filename):
        "Return True if the given file is an ELF file"
        elf_header = b'\x7fELF'
        with open(filename, 'br') as thefile:
            return thefile.read(4) == elf_header

**Comment by work-manong** [comment]
已解决 解决办法：

cd /usr/lib/x86_64-linux-gnu

ln -s -f libc.a liblibc.a

**Comment by ChloeKiwi** [comment]
请问大家有没有遇到配置好mysql后仍然连接不上的情况：
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '192.168.80.131' (timed out)")
(Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by cmluZw** [comment]
连不上请改成127.0.0.1或者localhost

**Comment by lauy14** [comment]
您好 请问搭建好了登录成功但是界面渲染部分缺失这个您有经验吗

**Comment by cmluZw** [comment]
具体哪部分缺失，麻烦细说，刚运行如果世界地图缺失那是应该的，因为没数据

**Comment by cmluZw** [comment]
> 您好 请问搭建好了登录成功但是界面渲染部分缺失这个您有经验吗

具体哪部分缺失，麻烦细说，刚运行如果世界地图缺失那是应该的，因为没数据

**Comment by Lolydawn** [comment]
http://49.232.56.132:9125/ 您帮忙看看这是啥问题 感觉很卡顿

**Comment by cmluZw** [comment]
> http://49.232.56.132:9125/ 您帮忙看看这是啥问题 感觉很卡顿

可能是日志太大，读取速度慢

**Comment by Lolydawn** [comment]
> > http://49.232.56.132:9125/ 您帮忙看看这是啥问题 感觉很卡顿
> 
> 可能是日志太大，读取速度慢

您指的是apache的日志吗 还是您的态势感知系统的日志 如果是后者的话 日志位置是在哪呢？麻烦您了

**Comment by cmluZw** [comment]
> > > http://49.232.56.132:9125/ 您帮忙看看这是啥问题 感觉很卡顿
> > 
> > 
> > 可能是日志太大，读取速度慢
> 
> 您指的是apache的日志吗 还是您的态势感知系统的日志 如果是后者的话 日志位置是在哪呢？麻烦您了

建议清空数据库后重新运行，如果还是异常缓慢，极有可能是apache/ssh的日志太多

**Comment by smileatme-094** [comment]
ERROR:app:Exception on /index [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "app.py", line 224, in index
    sshcharts, risk_index = sshCharts.sshPieCharts()
  File "/var/www/html/Situational-Awareness-1.3/Situational-Awareness-1.3/charts/sshCharts.py", line 39, in sshPieCharts
    streams = json.load(fp)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 460)
这是json的问题吗，不知道该咋修

**Comment by hohoha638** [comment]
从github替换https://github.com/cmluZw/Situational-Awareness/blob/master/output/analyse/network/flowStatistics.txt这个文件
这一步我有点不太明白，是要把原来的flowstatistics替换掉，用哪个替换呢

**Comment by cmluZw** [comment]
> 从github替换[https://github.com/cmluZw/Situational-Awareness/blob/master/output/analyse/network/flowStatistics.txt这个文件](https://github.com/cmluZw/Situational-Awareness/blob/master/output/analyse/network/flowStatistics.txt%E8%BF%99%E4%B8%AA%E6%96%87%E4%BB%B6) 这一步我有点不太明白，是要把原来的flowstatistics替换掉，用哪个替换呢

就是用没运行的压缩包里的flowStatistics.txt覆盖已经在运行的flowStatistics.txt

**Comment by hohoha638** [comment]
好的，已解决，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年7月30日(周三) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cmluZw/Situational-Awareness] 如遇报错请先看这 (Issue #6)


cmluZw left a comment (cmluZw/Situational-Awareness#6)
  
从github替换https://github.com/cmluZw/Situational-Awareness/blob/master/output/analyse/network/flowStatistics.txt这个文件 这一步我有点不太明白，是要把原来的flowstatistics替换掉，用哪个替换呢
  
就是用没运行的压缩包里的flowStatistics.txt覆盖已经在运行的flowStatistics.txt

**Comment by LSP1025923** [comment]
root@shisai-virtual-machine:/opt/Situational-Awareness-1.3/Situational-Awareness-1.3# python3 app.py 
[]
 * Serving Flask app 'app'
 * Debug mode: off
INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.107.197:5000
INFO:werkzeug:Press CTRL+C to quit
['192.168.107.1', ':0', 'boot', 'Mon']
0 []
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Situational-Awareness-1.3/Situational-Awareness-1.3/admin/manage/dangerous_manage.py", line 127, in danger
    for i in danger_list:
TypeError: 'int' object is not iterable
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /index HTTP/1.1" 200 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/css/demo.css HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/css/normalize.css HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/css/component.css HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/EasePack.min.js HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/TweenLite.min.js HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/rAF.js HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/demo-1.js HTTP/1.1" 304 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/img/demo-1-bg.jpg HTTP/1.1" 404 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/img/login_ico.png HTTP/1.1" 404 -
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:14] "POST /login HTTP/1.1" 302 -
1
192.168.107.1
The address 192.168.107.1 is not in the database.
[]
ERROR:app:Exception on /index [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2529, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 224, in index
    sshcharts, risk_index = sshCharts.sshPieCharts()
  File "/opt/Situational-Awareness-1.3/Situational-Awareness-1.3/charts/sshCharts.py", line 39, in sshPieCharts
    streams = json.load(fp)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 460)
INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:14] "GET /index HTTP/1.1" 500 -
^C^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by cmluZw** [comment]
> root@shisai-virtual-machine:/opt/Situational-Awareness-1.3/Situational-Awareness-1.3# python3 app.py []
> 
> * Serving Flask app 'app'
> * Debug mode: off
>   INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
> * Running on all addresses (0.0.0.0)
> * Running on http://127.0.0.1:5000
> * Running on http://192.168.107.197:5000
>   INFO:werkzeug:Press CTRL+C to quit
>   ['192.168.107.1', ':0', 'boot', 'Mon']
>   0 []
>   Exception in thread Thread-2:
>   Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
>   self.run()
>   File "/usr/lib/python3.8/threading.py", line 870, in run
>   self._target(*self._args, **self._kwargs)
>   File "/opt/Situational-Awareness-1.3/Situational-Awareness-1.3/admin/manage/dangerous_manage.py", line 127, in danger
>   for i in danger_list:
>   TypeError: 'int' object is not iterable
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /index HTTP/1.1" 200 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/css/demo.css HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/css/normalize.css HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/css/component.css HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/EasePack.min.js HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/TweenLite.min.js HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/rAF.js HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/js/demo-1.js HTTP/1.1" 304 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/img/demo-1-bg.jpg HTTP/1.1" 404 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:11] "GET /static/img/login_ico.png HTTP/1.1" 404 -
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:14] "POST /login HTTP/1.1" 302 -
>   1
>   192.168.107.1
>   The address 192.168.107.1 is not in the database.
>   []
>   ERROR:app:Exception on /index [GET]
>   Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2529, in wsgi_app
>   response = self.full_dispatch_request()
>   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1825, in full_dispatch_request
>   rv = self.handle_user_exception(e)
>   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1823, in full_dispatch_request
>   rv = self.dispatch_request()
>   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1799, in dispatch_request
>   return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
>   File "app.py", line 224, in index
>   sshcharts, risk_index = sshCharts.sshPieCharts()
>   File "/opt/Situational-Awareness-1.3/Situational-Awareness-1.3/charts/sshCharts.py", line 39, in sshPieCharts
>   streams = json.load(fp)
>   File "/usr/lib/python3.8/json/**init**.py", line 293, in load
>   return loads(fp.read(),
>   File "/usr/lib/python3.8/json/**init**.py", line 357, in loads
>   return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
>   raise JSONDecodeError("Extra data", s, end)
>   json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 460)
>   INFO:werkzeug:192.168.107.1 - - [22/Sep/2025 02:58:14] "GET /index HTTP/1.1" 500 -
>   ^C^CException ignored in: <module 'threading' from '/usr/lib/python3.8/threading.py'>
>   Traceback (most recent call last):
>   File "/usr/lib/python3.8/threading.py", line 1388, in _shutdown
>   lock.acquire()
>   KeyboardInterrupt:

程序没退出就没问题
